version: "3.9" 
services:
  web:
    build: .
    ports:
      - "8000:5000"
    volumes:
      - .:/code
      - logvolume01:/var/log
    links:
      - redis
  redis:
    image: redis
volumes:
  logvolume01: {}
--db 'mongodb+srv://luxxyxyz:<luxxyxyz>@cluster0.lg2pn.mongodb.net/?retryWrites=true&w=majority'
